query getArticle ($slug: String){
  fetchedArticle: articles(where: {slug: $slug}, limit: 1) {
    id
    title
    content
    created_at
    author
    enableComments
    image {
      formats
    }
  }
}
