query ($articleId: String){
  articleComments (where: {article: $articleId}, sort: "created_at:asc"){
    comment
    created_at
    user: users_permissions_user {
      username
      id
    }
    commentStatus
  }
}
