query ($limit: Int) {
  lastArticles: articles(limit: $limit, sort: "created_at:desc") {
    id
    title
    slug
    imageUrl: image {
      formats
    }
    created_at
    author
    content
    article_categorie {
      category
      backgroundColor
    }
  }
}
