version: "3"
services:
  back:
    build: ./taddart-back
    container_name: taddart-back-container
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=td-strapi
      - DATABASE_USERNAME=td-strapi
      - DATABASE_PASSWORD=td-strapi
      - DATABASE_SCHEMA=public
    ports:
      - "1337:1337"
    networks:
      - strapi-app-network

  front:
    build: ./taddart-front
    container_name: taddart-front-container
    environment:
      - BACKEND_URL=http://10.0.3.24:1337/graphql
    ports:
      - "3000:3000"
    networks:
      - strapi-app-network

  db:
    container_name: mysql-strapi
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: td-strapi
      MYSQL_USER: td-strapi
      MYSQL_PASSWORD: td-strapi
      MYSQL_ROOT_PASSWORD: td-strapi
    networks:
      - strapi-app-network
    ports:
      - 3306:3306

networks:
  strapi-app-network:
    driver: bridge
