query ($locale: String){
  fileContents (locale: $locale){
    title
    author
    thumbnail {
      formats
    }
    fileUrl:file {
      url
    }
    file_content_category {
      id
    }
  }
}
