version: '3'
services:
  db:
    container_name: mysql-strapi
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: td-strapi
      MYSQL_USER: td-strapi
      MYSQL_PASSWORD: td-strapi
      MYSQL_ROOT_PASSWORD: td-strapi
    ports:
      - 3316:3306
